### ISSUE TITLE
Where are we passing the API key that we generate?

### ISSUE THREAD

**Issue by kevinlu1211** [jonnekaunisto/simple-youtube-api#12]
Hello and thanks for this library, I was wondering where do we pass the API Key that we have generated from GCP? It seems like you are using OAuth. Also, how do we specify which channel we want to upload to, is this generated in the `client_secret.json`? If so, I'm a bit confused as the application that I have created in GCP isn't linked to any YouTube account.

**Comment by kevinlu1211** [comment]
Don't worry I figured it out I had to create desktop OAuth Token

**Comment by jonnekaunisto** [comment]
Good that you were able to figured it out.

Do you think there is anything that should be added to the documentation that could alleviate any confusion people have trying to use this library?

I guess I should write some instructions on how to get and use the client_secret.json.
