### ISSUE TITLE
option to set made for kids or not 

### ISSUE THREAD

**Issue by lukelu0520** [jonnekaunisto/simple-youtube-api#15]
Dear jonnekaunisto,

Marking "Made for kids or not" now is required by Youtube & COPPA. 
I was wondering if there is medata available in simple-youtube-api, e.g. video.made_for_kids(False), for video upload.

Hope to hear your expertise. Thank you!

**Comment by jonnekaunisto** [comment]
It is not yet implemented, but I will try to add it soon. 

Thanks for noticing that!

**Comment by jonnekaunisto** [comment]
I've added that feature on the latest version now.

**Comment by lukelu0520** [comment]
Hi jonnekaunisto,

Thanks for your great support. I've used the new feature, it works very well !
A big star can not express my appreciation on your dedication !
I am continuously using and testing the program, hope to provide you more feedback.
