### ISSUE TITLE
Set playlist for video upload

### ISSUE THREAD

**Issue by lukelu0520** [jonnekaunisto/simple-youtube-api#17]
Dear jonnekaunisto,

Thanks for your dedicated supports. We recently found an important feature, hope to hear your expertise.

Our channel has multiple playlists, and we would like to upload a video assigned to desire playlist s.t. video.set_playlist("This is my playlist name"), (it could be None if the playlist does not exist etc)

It would be super useful because our numbers of video are increasing.

We were wondering if you have any thought on the feature.

**Comment by jonnekaunisto** [comment]
I've added that feature in the newest version. You have to supply the playlist id in order to add a video to it.
