### ISSUE TITLE
What should the value of credentials.storage ?

### ISSUE THREAD

**Issue by KetanIP** [jonnekaunisto/simple-youtube-api#32]

**Comment by jonnekaunisto** [comment]
The first time you run the ``channel.login()`` it will prompt you to login to your Google account and once you're done with that the credentials.storage file will be generated in the directory that you set it to be in.

Now if you call ``channel.login()`` again then it will use the credentials in the credentials.storage file.

Does that make sense?

**Comment by KetanIP** [comment]
Yes it makes sense to me. Thank You sir. 🙂
